//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAppManagementPoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg
    {
        public string Student_id { get; set; }
        public string First_Name { get; set; }
        public string Last_name { get; set; }
        public Nullable<int> Course_Code { get; set; }
        public Nullable<int> Module_Code { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual SelfStudy SelfStudy { get; set; }
    }
}
