//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAppManagementPoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfStudy
    {
        public string Module_Code { get; set; }
        public string Module_Name { get; set; }
        public string Module_Credit { get; set; }
        public string Class_Hours_Per_Week { get; set; }
        public string StartDate { get; set; }
    
        public virtual Reg Reg { get; set; }
    }
}
